language: ruby
rvm:
  - 2.4.1

# https://stackoverflow.com/questions/57758654/why-do-i-get-could-not-find-bundler-1-17-3-after-upgrading-ruby
# Fixes: Could not find 'bundler' (1.17.3) required by your Gemfile.lock
before_install:
 - gem install bundler:1.17.3

before_script:
 - chmod +x ./script/cibuild.sh # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild.sh

# branch whitelist, only for GitHub Pages
#branches:
#  only:
#  - master  # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false